[story] card_146 インスタ連携機能実装
saganoH/InstaExt pull request #11
Opened 2021-02-24 02:31 UTC by saganoH

https://trello.com/c/p4GOZdCN/146-15-%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E9%80%A3%E6%90%BA%E6%A9%9F%E8%83%BD%E5%AE%9F%E8%A3%85-9

2021-02-24 04:31 UTC, TakahiroAnamizu requested changes
挙動について指摘&質問
* Appleは写真権限についてlimitedでも使えるようにしなさいと明文化してます 。現在の挙動は違反しているので、仕様の再検討をお願いします
* InstaIconの配置位置について、navBar中央に配置するのはあまり見かけたことないですが、参考アプリなどありますか？
    *  一般的には左右に寄せて複数配置していることが多いです

2021-02-24 04:58 UTC, taketomato requested changes
全体的によく書けていると思います！
`alert` の生成とか表示は共通化できそうなところもありますが、nice to have ですね。

2021-02-24 04:58 UTC, taketomato commented on InstaExt/InstaExt/InstaLinker.swift
> +class InstaLinker: NSObject {
`NSObject` を継承する必要はなさそうです。
参考としては [ここ](https://www.mpon.me/entry/2015/08/13/174157) とか

2021-02-24 04:58 UTC, taketomato commented on InstaExt/InstaExt/InstaLinker.swift
> +        if (fetchResult.firstObject != nil) {
1行下の `guard` でチェックするようにするとネストが1つ減ります。

2021-02-24 04:58 UTC, taketomato commented on InstaExt/InstaExt/InstaLinker.swift
> +                DispatchQueue.main.async {
`delegate` 先で `show` する作りになっているので、ここはメインキューにする必要ないです。

2021-02-24 04:58 UTC, taketomato commented on InstaExt/InstaExt/InstaLinker.swift
> +    func showInstaAlert(alert: UIAlertController)
`show`するのは画面側の責務になるので、`failedToLink(with alert:)`的な名前の方がより適切と思います。

2021-02-24 04:58 UTC, taketomato commented on InstaExt/InstaExt/MainViewController.swift
> +            self.present(alert, animated: true)
テクニックというか好みになる感じもありますが、`self`をアンラップせずに
`self?.present(alert, animated: true)` という書き方もできて、この場合 `self` が `nil` の場合は実行されないだけ。になります。

2021-02-24 05:06 UTC, saganoH commented on InstaExt/InstaExt/InstaLinker.swift
> +class InstaLinker: NSObject {
`NSObject`を継承しない場合、`Unrecognized selector`と表示されて止まってしまうのですが、何か別の方法をとる必要がありますか？

2021-02-24 05:17 UTC, saganoH commented on InstaExt/InstaExt/InstaLinker.swift
> +        if (fetchResult.firstObject != nil) {
その通りですね。プラスで、`guard let lastAsset = fetchResult.lastObject〜`のみで十分だと気づいたのでif文削除しました。

2021-02-24 05:29 UTC, TakahiroAnamizu requested changes

2021-02-24 05:29 UTC, ghost commented on InstaExt/InstaExt/InstaLinker.swift
> +        UIImageWriteToSavedPhotosAlbum(image, self, #selector(afterSave(_:didFinishSavingWithError:contextInfo:)), nil)
連続でInsta連携すると、デバイス内に同じ画像が複数できてしまいます
初回のみ必須にするなど複数生成されないような工夫があるとベター

2021-02-24 05:29 UTC, TakahiroAnamizu commented on InstaExt/docs/クラス図.plantuml
> +  @objc 画像のURLを取得しインスタへ遷移
Viewerで見ると、プロパティの区分に表示されてる？
(よく見たらメイン画面とかもなので、自前で区切り線書く必要ありそう)

2021-02-24 05:30 UTC, saganoH commented on InstaExt/InstaExt/InstaLinker.swift
> +                DispatchQueue.main.async {
その通り修正しました。

2021-02-24 05:41 UTC, saganoH commented on InstaExt/InstaExt/InstaLinker.swift
> +    func showInstaAlert(alert: UIAlertController)
修正しました。

2021-02-24 05:42 UTC, taketomato commented on InstaExt/InstaExt/InstaLinker.swift
> +class InstaLinker: NSObject {
落ちちゃいますね。`#selector`する場合は、継承する必要があるのか。
この指摘は取り下げます。

2021-02-24 05:44 UTC, taketomato commented
追加ですみません。
起動後画像が選択されていない状態で、連携ボタン押しても何も起きなくてあれ？ってなります。

2021-02-24 05:46 UTC, saganoH commented on InstaExt/InstaExt/MainViewController.swift
> +            self.present(alert, animated: true)
その通り直してみたら1行無くなっただけでスッキリしました、ありがとうございます。

2021-02-24 05:52 UTC, taketomato commented
このカードと関係ないんですが、シミュレータに入っている赤い花のサンプルが開けないのが気になりました。
写真アプリみるとこの画像だけ HDR になっているよう。

2021-02-24 05:56 UTC, saganoH commented on InstaExt/docs/クラス図.plantuml
> +  @objc 画像のURLを取得しインスタへ遷移
()つけ忘れていたので修正しました

2021-02-24 05:58 UTC, saganoH commented on InstaExt/InstaExt/InstaLinker.swift
> +        UIImageWriteToSavedPhotosAlbum(image, self, #selector(afterSave(_:didFinishSavingWithError:contextInfo:)), nil)
同じ画像を連続で投稿するような使い方はテスト以外だとないかなと思うのですが、考えた方が良いでしょうか？

2021-02-24 05:59 UTC, saganoH commented
> 追加ですみません。
> 起動後画像が選択されていない状態で、連携ボタン押しても何も起きなくてあれ？ってなります。

2021-02-24 06:04 UTC, saganoH commented
> 追加ですみません。
> 起動後画像が選択されていない状態で、連携ボタン押しても何も起きなくてあれ？ってなります。

何かメッセージを出した方がいいかなとも考えたのですが、初期メッセージ「画像を選択してください」と重複するのでいらないかな？と思っていました。

2021-02-24 06:16 UTC, saganoH commented
> このカードと関係ないんですが、シミュレータに入っている赤い花のサンプルが開けないのが気になりました。
> 写真アプリみるとこの画像だけ HDR になっているよう。

 @taketomato 
シミュレータのみで起こるバグのようです。
https://developer.apple.com/forums/thread/665265

2021-02-24 06:24 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/InstaLinker.swift
> +        UIImageWriteToSavedPhotosAlbum(image, self, #selector(afterSave(_:didFinishSavingWithError:contextInfo:)), nil)
先に画像保存してからInsta連携するケースでは2枚できてしまうので違和感がある可能性を考えてました

2021-02-24 06:41 UTC, saganoH commented on InstaExt/InstaExt/InstaLinker.swift
> +        UIImageWriteToSavedPhotosAlbum(image, self, #selector(afterSave(_:didFinishSavingWithError:contextInfo:)), nil)
なるほど、確かにそうですね。
考えてみます。

2021-02-24 07:52 UTC, taketomato commented
> 何かメッセージを出した方がいいかなとも考えたのですが、初期メッセージ「画像を選択してください」と重複するのでいらないかな？と思っていました。

確認したら保存ボタンも同じで、編集3兄弟は編集画面に遷移しちゃうんですね。

世の中に出すアプリなら「これをするには画像の選択が必要です」的なメッセージ出すか、ボタンを無効にするかあたりが必要ですが、OJTアプリとしては nice to have での対応で良いと思います。

2021-02-24 07:57 UTC, saganoH commented
> 確認したら保存ボタンも同じ動きで、編集3兄弟の場合は編集画面に遷移しちゃうんですね。
> 
> 世の中に出すアプリなら「これをするには画像の選択が必要です」的なメッセージ出すか、ボタンを無効にするかあたりが必要ですが、OJTアプリとしては nice to have での対応で良いと思います。

保存ボタンとインスタボタンは画像選択するまでは無効化にしました。
編集のやつはボタンじゃなくてコレクションビューなのでこれから少し調べます。

2021-02-24 08:30 UTC, taketomato requested changes

2021-02-24 08:30 UTC, taketomato commented on InstaExt/InstaExt/InstaLinker.swift
> +            return
ここも`self.delegate?.failedToLink(with: alert)`必要ですね。。。
追加指摘でごめんなさい。

2021-02-25 00:50 UTC, saganoH commented on InstaExt/InstaExt/InstaLinker.swift
> +            return
アラート追加しました。

2021-02-25 00:52 UTC, saganoH commented
> > 確認したら保存ボタンも同じ動きで、編集3兄弟の場合は編集画面に遷移しちゃうんですね。
> > 世の中に出すアプリなら「これをするには画像の選択が必要です」的なメッセージ出すか、ボタンを無効にするかあたりが必要ですが、OJTアプリとしては nice to have での対応で良いと思います。
> 
> 保存ボタンとインスタボタンは画像選択するまでは無効化にしました。
> 編集のやつはボタンじゃなくてコレクションビューなのでこれから少し調べます。

編集機能のcellも無効化しました。
無効/有効で色を変えたいところですが、時間がかかりそうとのことだったので別カード化しました。

2021-02-25 00:58 UTC, taketomato commented on InstaExt/InstaExt/InstaLinker.swift
> +            return
こうなると OK ボタンは共通なので、title と message を渡すと alertController を返してくれるメソッド切り出したくなりますね。

2021-02-25 01:18 UTC, saganoH commented on InstaExt/InstaExt/InstaLinker.swift
> +            return
切り出してみました。

2021-02-25 01:19 UTC, saganoH commented on InstaExt/InstaExt/InstaLinker.swift
> +            return
fetchの方は動作確認で通らないので、共通化したほうがいいことがわかりました。

2021-02-25 01:30 UTC, taketomato approved these changes
approved! いろいろ追加指摘してしまいすみませんでした。

2021-02-25 02:00 UTC, saganoH commented on InstaExt/InstaExt/InstaLinker.swift
> +        UIImageWriteToSavedPhotosAlbum(image, self, #selector(afterSave(_:didFinishSavingWithError:contextInfo:)), nil)
別カード化済

2021-02-25 02:29 UTC, TakahiroAnamizu approved these changes

2021-02-25 02:30 UTC, merged