[story] card_149 モザイク機能実装
saganoH/InstaExt pull request #16
Opened 2021-03-02 04:47 UTC by saganoH

https://trello.com/c/pX3aCxfv/149-5-%E3%83%A2%E3%82%B6%E3%82%A4%E3%82%AF%E6%A9%9F%E8%83%BD%E5%AE%9F%E8%A3%85

2021-03-02 07:42 UTC, TakahiroAnamizu requested changes
.swiftファイルが増えてきたので、フォルダ分けすると良いと思います

2021-03-02 07:42 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/Filter.swift
> +            return 70
リファレンス読むとinputScaleの範囲は1-100ですが、70までにした理由は何かありますか？

2021-03-02 08:05 UTC, saganoH commented on InstaExt/InstaExt/Filter.swift
> +            return 70
範囲を広くするとスライダで調整しにくいので、顔がアップの写真にモザイクがかかる程度の70をmaxに設定しました

2021-03-03 01:11 UTC, saganoH commented on InstaExt/InstaExt/Filter.swift
> +            return 70
max70: 画質良い顔がアップの写真にモザイクがかけられる程度
min5: 画質が悪い引きの写真にモザイクがかけられる程度
と修正しました。

2021-03-03 01:23 UTC, TakahiroAnamizu approved these changes

2021-03-03 01:56 UTC, ShuheiOno commented on InstaExt/InstaExt/Filter/Mosaic.swift
> +        let monochromeFilter = CIFilter(name: "CIPixellate")!
強制unwrapしてますが、unwrapに失敗したときのことは考慮されてますか？

2021-03-03 02:04 UTC, ShuheiOno commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +
この処理が入った理由を教えて下さい

2021-03-03 02:14 UTC, ShuheiOno commented on InstaExt/InstaExt/Filter/Filter.swift
> +            return 70
[質問]70に設定した根拠を教えて下さい

2021-03-03 02:15 UTC, ShuheiOno commented on InstaExt/InstaExt/Filter/Filter.swift
> +            return 5
[質問]同様に、5に設定した根拠を教えて下さい

2021-03-03 02:22 UTC, ShuheiOno commented
全体的にこれまでのレビューで指摘されていたことが反映されているため、
このプルリクに関して言えば、私からの指摘事項はありません。

強いて言えば、今回のレビュー範囲外ですが、アプリ全体を見てみて、
エラーメッセージの表現がぶれていることが気になります。
MaskViewのL15だけが英語のメッセージだったり、
「〇〇できませんでした」という丁寧語の表現と「〇〇の生成に失敗」という表現が混在してます。
もし意図して使い分けているのであれば、その意図が妥当なものであれば修正の必要はありません。
単に表現のブレであればどちらかに統一したほうがいいですね。

2021-03-03 02:38 UTC, saganoH commented
すみません、バグって個別にコメントできなくなってしまったのでまとめて書きます。

・CIFilterの生成に関しては、nilになるケースがミスタイプだけなので落とすために強制アンラップしています。
・EditerViewControllerのL23の追加処理は、今回のモザイクフィルタのみフィルタをかけた後`viewDidLayoutSubviews`が走ってしまうため、なぞった部分のマスクを再生成しないように判定を追加しています。
・5-70の値設定に関しては、取れる範囲1-100の中で、画質良い画像でも悪い画像でもモザイクがかかるように微調整をしました。
・メッセージの表記ブレに関しては、ユーザーに出すアラートは丁寧語 / 落ちた場合の自分が見るメッセージは言い切りの形にしています。英語と日本語の表記ブレは意図していなかったため修正しました。

2021-03-03 02:57 UTC, ShuheiOno commented
・強制unwrapの件、了解です。(指摘書いたあと、尾方さんとのレビューで同じこと書いてあったので消したのですが、すでに呼んだあとでしたかね）

・EditViewControllerの処理の件、了解です。

・メッセージの表現の使い分け、意図があったとのこと、了解です。いいと思います。
   MaskViewのメッセージが修正されてることを確認しました。
   (ここも自分が見る目的のメッセージという目的なら、英語でもいいと言えばいいですけどね。)

2021-03-03 04:08 UTC, ShuheiOno approved these changes

2021-03-03 04:12 UTC, merged