[story] card_167 画像形式揃えの実装
saganoH/InstaExt pull request #17
Opened 2021-03-03 06:19 UTC by saganoH

https://trello.com/c/rjc6MV6G/167-5-%E7%94%BB%E5%83%8F%E5%BD%A2%E5%BC%8F%E6%8F%83%E3%81%88%E3%81%AE%E5%AE%9F%E8%A3%85-1

コンフリクト時に消えたファイルの復元でコミットが一部二重になってしまい、見づらくて申し訳ないです

2021-03-03 07:17 UTC, TakahiroAnamizu requested changes

2021-03-03 07:17 UTC, ghost commented on InstaExt/InstaExt/InOut/ImageDelivery.swift
> +        guard let convertedImage = UIImage(data: convertedData) else { return source }
guard文を1つにまとめて良さそう

2021-03-03 07:17 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/InOut/ImageDelivery.swift
> +        guard let convertedImage = UIImage(data: convertedData) else { return source }
変換失敗した場合、そのままの画像が変えるようになってますが、保存される画像拡張子はどうなりますか？

2021-03-03 07:17 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/InOut/ImageDelivery.swift
> +        provider.loadObject(ofClass: UIImage.self, completionHandler: { [weak self] (selectedImage, error) in
L89 `loadItem`の処理が完了する前にdelegateが実行される可能性がありますが、考慮した上での実装でしょうか？
`loadItem`、`loadObject`どちらも非同期処理なので、どちらが先に完了するかはわかりません(重い処理ではないので問題ないと思いますが)

2021-03-03 07:17 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/InOut/ImageDelivery.swift
> +        provider.loadItem(forTypeIdentifier: identifier, options: nil) { (url, error) in
ここだけTrailingClosureになっていて、他の箇所とばらつきがあります

2021-03-03 07:32 UTC, saganoH commented on InstaExt/InstaExt/InOut/ImageDelivery.swift
> +        guard let convertedImage = UIImage(data: convertedData) else { return source }
guard文まとめました
(guardで定義している変数を使ってguardする場合、まとめてかけないと思ってました)

2021-03-03 07:35 UTC, consasap12 commented
数値リテラルの書き方が
[ここ](https://github.com/saganoH/InstaExt/blob/develop/InstaExt/InstaExt/MaskProcess/MaskView.swift#L36) のようにあらかじめ定義があったり
[ここ](https://github.com/saganoH/InstaExt/blob/develop/InstaExt/InstaExt/InOut/ImageDelivery.swift#L11) のように直接代入していたり
となっているので、どちらかに統一されているのが好ましくて、
更に突っ込むと、後で微調整したかったりなものはクラス定数にするなどがあると、さらに良くなりそうです。
文字リテラルについても同様。

一般的にはコーディング規約で決まってたりするものですし、今回はそこまで厳密じゃないかもなので、統一を心がけてると将来的に良いかも、程度です。
微々たるものですが、変数準備と保持するメモリ容量とコピーする処理時間が不要なので、個人的にはリテラルは全て直接代入を好んでますが、そこは何に使う値なのか、書いた人、参加してるテーマなどによって異なるかと思います。

2021-03-03 07:45 UTC, saganoH commented on InstaExt/InstaExt/InOut/ImageDelivery.swift
> +        guard let convertedImage = UIImage(data: convertedData) else { return source }
変換失敗の場合の拡張子は把握しきれていませんが
ストレージとかの問題で画像生成ができなかったくらいしかnilになる可能性ないかなと考えていました
画像保存自体はできるので処理は続行させた方が良いと考えてそのまま元画像を返しています

2021-03-03 07:50 UTC, saganoH commented on InstaExt/InstaExt/InOut/ImageDelivery.swift
> +        provider.loadObject(ofClass: UIImage.self, completionHandler: { [weak self] (selectedImage, error) in
`loadItem`、`loadObject`どちらが先に完了するかわからないというところは把握していましたが、
delegateが先に実行される可能性までは考えていませんでした。
delegateで画像を設定しているので、画像を取得完了前にdelegate実行されると困りますね、、、

2021-03-03 07:53 UTC, saganoH commented on InstaExt/InstaExt/InOut/ImageDelivery.swift
> +        provider.loadItem(forTypeIdentifier: identifier, options: nil) { (url, error) in
気がつきませんでした！修正します

2021-03-03 07:55 UTC, TakahiroAnamizu requested changes

2021-03-03 07:55 UTC, TakahiroAnamizu commented on InstaExt/docs/クラス図.plantuml
> +enum 画像形式 {
どこで使われているのか不明なので紐付けしましょう(フィルタタイプもお願いします)

2021-03-03 07:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/InOut/ImageDelivery.swift
> +        provider.loadObject(ofClass: UIImage.self, completionHandler: { [weak self] (selectedImage, error) in
`loadItem`のclosureの中で`loadObject`を実行すれば期待通りの制御ができますが、処理時間の影響は確認しなければならないですね

2021-03-03 07:58 UTC, saganoH commented
> 数値リテラルの書き方が
> [ここ](https://github.com/saganoH/InstaExt/blob/develop/InstaExt/InstaExt/MaskProcess/MaskView.swift#L36) のようにあらかじめ定義があったり
> [ここ](https://github.com/saganoH/InstaExt/blob/develop/InstaExt/InstaExt/InOut/ImageDelivery.swift#L11) のように直接代入していたり
> となっているので、どちらかに統一されているのが好ましくて、
> 更に突っ込むと、後で微調整したかったりなものはクラス定数にするなどがあると、さらに良くなりそうです。
> 文字リテラルについても同様。
> 
> 一般的にはコーディング規約で決まってたりするものですし、今回はそこまで厳密じゃないかもなので、統一を心がけてると将来的に良いかも、程度です。
> 微々たるものですが、変数準備と保持するメモリ容量とコピーする処理時間が不要なので、個人的にはリテラルは全て直接代入を好んでますが、そこは何に使う値なのか、書いた人、参加してるテーマなどによって異なるかと思います。

なんとなくで書いてしまっているところが多かったです、見直して修正します。

2021-03-03 08:00 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/InOut/ImageDelivery.swift
> +        guard let convertedImage = UIImage(data: convertedData) else { return source }
変換失敗は拡張子保存できないがjpg保存はできるようにするということですね、了解です

2021-03-04 01:03 UTC, saganoH commented on InstaExt/InstaExt/InOut/ImageDelivery.swift
> +        provider.loadItem(forTypeIdentifier: identifier, options: nil) { (url, error) in
他の部分にも見つけたので修正しました

2021-03-04 01:07 UTC, saganoH commented on InstaExt/InstaExt/InOut/ImageDelivery.swift
> +        provider.loadObject(ofClass: UIImage.self, completionHandler: { [weak self] (selectedImage, error) in
> delegateで画像を設定しているので、画像を取得完了前にdelegate実行されると困りますね、、
これは空目していた勘違い
正しくは、画像取得→delegate実行は保証されていて、URLの取得が間に合わない可能性がある

2021-03-04 01:08 UTC, saganoH commented on InstaExt/InstaExt/InOut/ImageDelivery.swift
> +        provider.loadObject(ofClass: UIImage.self, completionHandler: { [weak self] (selectedImage, error) in
delegate実行前にURL取得も完了するよう修正しました

2021-03-04 01:08 UTC, consasap12 approved these changes

2021-03-04 01:20 UTC, saganoH commented on InstaExt/docs/クラス図.plantuml
> +enum 画像形式 {
修正しました！

2021-03-04 01:41 UTC, TakahiroAnamizu approved these changes

2021-03-04 01:41 UTC, merged