Card 144
saganoH/InstaExt pull request #2
Opened 2021-01-21 04:44 UTC by saganoH

https://trello.com/c/2DQC3cU1/144-3-%E5%86%99%E7%9C%9F%E5%8F%96%E3%82%8A%E8%BE%BC%E3%81%BF%E6%A9%9F%E8%83%BD%E5%AE%9F%E8%A3%85-2

2021-01-21 04:46 UTC, saganoH commented
今後の検討事項
・画像開いている状態で2回目取り込みしようとした時に何らかの防止策欲しい
・Deviceクラスの取り込みメソッドでどこまで行うか（設計の見直し）

2021-01-21 05:21 UTC, TakahiroAnamizu requested changes
コメントの中に不要そうなものがあるので、リーダブルコードを意識して厳選してみましょう
(個人的には、コメントなしでも十分読めるコードだと思います)

2021-01-21 05:21 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/Device.swift
> +                    print("error: \(error.localizedDescription)")
このエラーが出た時、print文だけで良いでしょうか？
ユーザは何をしていいか分からないのでは？と思いました

2021-01-21 05:21 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/Device.swift
> +                    print("wrap error")
こちらのprint文も同様

2021-01-21 05:21 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MainViewController.swift
> +    private var mainImage: UIImage = UIImage(named: "transparentImage")!
transparentImageはどういう目的のものでしょうか？

2021-01-21 05:21 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/Device.swift
> +class Device {
`Device`だと責務が曖昧なのでもう少し適切な命名をしたいですね
画像のIn/Outが責務であれば、ImageProviderなど具体的な方が良いと思います

2021-01-21 05:21 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MainViewController.swift
> +    private let deviceC = Device()
Cに何か意味はありますか？なくても良さそうに思います

2021-01-21 05:25 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/Device.swift
> +class Device {
Providerは供給なので少し違いますね

2021-01-21 05:27 UTC, saganoH commented on InstaExt/InstaExt/MainViewController.swift
> +    private let deviceC = Device()
classの意味で習慣的に書いてしまっていました、消します

2021-01-21 05:28 UTC, saganoH commented on InstaExt/InstaExt/MainViewController.swift
> +    private var mainImage: UIImage = UIImage(named: "transparentImage")!
本当はprivate var mainImage: UIImageだけにしたいのですが、初期化しろってメッセージが出るので苦し紛れに透明画像で初期化していました

2021-01-21 05:31 UTC, saganoH commented on InstaExt/InstaExt/Device.swift
> +                    print("error: \(error.localizedDescription)")
PHPickerの挙動を考えた際に、取得できずにユーザーに何か対処してもらうような場合を想像できませんでした
画像以外のものはそもそもカメラロールにないでしょうし、、、

2021-01-21 05:32 UTC, saganoH commented on InstaExt/InstaExt/Device.swift
> +class Device {
デバイスの何を扱っているのか、確かに曖昧ですね。修正します。

2021-01-21 05:42 UTC, saganoH commented on InstaExt/InstaExt/Device.swift
> +class Device {
受け渡し、でdeliveryとかですかね

2021-01-21 05:43 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/Device.swift
> +                    print("error: \(error.localizedDescription)")
可能性の1つとして、画像ファイルが破損しているケースはエラーになるケースが考えられます
なので、その画像は読み込めません的なメッセージくらいは出すと良さそうだと思いました
(本当はこのケースに来る状態に合わせてメッセージを変えたいですが検証が大変なので...)

2021-01-21 05:44 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MainViewController.swift
> +    private var mainImage: UIImage = UIImage(named: "transparentImage")!
mainImageはOptionalだとダメな理由があるってことですか？

2021-01-21 05:44 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MainViewController.swift
> +    private var mainImage: UIImage = UIImage(named: "transparentImage")!
命名もmainってなんだ？ってなるので適切な名前が欲しいところ

2021-01-21 05:47 UTC, saganoH commented on InstaExt/InstaExt/Device.swift
> +                    print("error: \(error.localizedDescription)")
なるほど！確かにiphoneでたまに真っ黒画像生成されてる時とかありますね。。
アラート出すようにします

2021-01-21 05:48 UTC, saganoH commented on InstaExt/InstaExt/Device.swift
> +                    print("wrap error")
アラートを出すメソッドを作っておいて、どちらかのエラーに入ったら実行させる、という感じにします

2021-01-21 05:51 UTC, saganoH commented on InstaExt/InstaExt/MainViewController.swift
> +    private var mainImage: UIImage = UIImage(named: "transparentImage")!
書いている時頭の中で何か引っかかってこうしたと思うのですが、今変えてみたらprivate var mainImage: UIImage!でも良さそうでした

2021-01-21 05:55 UTC, saganoH commented on InstaExt/InstaExt/MainViewController.swift
> +    private var mainImage: UIImage = UIImage(named: "transparentImage")!
MainViewControllerと対応する画像、という意味でmainImageとしていて、
EditorViewControllerの編集中画像はeditingImageにしようと思っていました
何とかImageが多くて命名が難しいですね、、

2021-01-21 06:00 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MainViewController.swift
> +    private var mainImage: UIImage = UIImage(named: "transparentImage")!
ここの画像というのは、開いた時の元画像の保持or編集後の画像も格納される、いずれかで大きく意味が異なりますね

2021-01-21 06:02 UTC, saganoH commented on InstaExt/InstaExt/MainViewController.swift
> +    private var mainImage: UIImage = UIImage(named: "transparentImage")!
編集後の画像も格納されますね
編集画面で編集確定させるたびに更新されるイメージです

2021-01-21 06:07 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MainViewController.swift
> +    private var mainImage: UIImage = UIImage(named: "transparentImage")!
imageView.imageに直接格納してはいけない理由とかあります？毎回更新の場合直接反映させても問題なさそうに思えます

2021-01-21 06:11 UTC, saganoH commented on InstaExt/InstaExt/MainViewController.swift
> +    private var mainImage: UIImage = UIImage(named: "transparentImage")!
デバイスクラスなどから直接セットできるように用意していたんだと思います(staticつけていたのもその考えによる)
現状いらない気がしてきました、、

2021-01-21 06:25 UTC, saganoH commented on InstaExt/InstaExt/Device.swift
> +                    print("error: \(error.localizedDescription)")
アラートをテストするのむずかしそうですが、実行しにくいエラー分岐を試す方法とかありますか？

2021-01-21 06:29 UTC, TakahiroAnamizu requested changes

2021-01-21 06:29 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/Device.swift
> +            image.itemProvider.loadObject(ofClass: UIImage.self) { (selectedImage, error) in
クロージャの中でself参照は循環参照のリスクがあるので弱参照にしましょう
これを参考にhttps://qiita.com/tarunon/items/6ac52a737ab49a967d6d

2021-01-21 06:31 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/Device.swift
> +                    print("error: \(error.localizedDescription)")
ここテストするのは難しいですね、安全策として書くのみで今は確認はしなくて良いかもしれないですね

2021-01-21 06:34 UTC, saganoH commented on InstaExt/InstaExt/Device.swift
> +                    print("error: \(error.localizedDescription)")
一応さっきの画像ないパターンのみ確認しました

エラーケースざっと調べてみたんですが、エラー分けするとなるとエラーの型が色々あって大変なんですね

2021-01-21 06:53 UTC, saganoH commented on InstaExt/InstaExt/Device.swift
> +            image.itemProvider.loadObject(ofClass: UIImage.self) { (selectedImage, error) in
問題なのはUIImage.selfのところですか？

2021-01-21 07:04 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/Device.swift
> +            image.itemProvider.loadObject(ofClass: UIImage.self) { (selectedImage, error) in
self.delegateが問題になります

2021-01-22 02:14 UTC, TakahiroAnamizu requested changes

2021-01-22 02:14 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ImageDelivery.swift
> +                }
後処理が同じなので、ここの条件まとめましょうか
```
guard error == nil,
      let wrapImage = selectedImage as? UIImage else {
    self.makePickerAlert(completion: { (alert) in self.delegate?.showAlert(alert: alert) })
    return
}
```

2021-01-22 02:23 UTC, TakahiroAnamizu approved these changes

2021-01-22 02:23 UTC, merged