[story] card_207 顔認識ぼかし機能
saganoH/InstaExt pull request #21
Opened 2021-03-11 05:11 UTC by saganoH

https://trello.com/c/geWHhBGX/207-13-%E9%A1%94%E8%AA%8D%E8%AD%98%E3%81%BC%E3%81%8B%E3%81%97%E6%A9%9F%E8%83%BD-13

2021-03-15 02:57 UTC, TakahiroAnamizu requested changes
デバッグ用？printが残ってるので、不要なものは消しましょう

2021-03-15 02:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +    // MARK: - public
MARKの下は1行空けましょう

2021-03-15 02:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +            maskView?.addGestureRecognizer(UIPanGestureRecognizer(target: maskView,
maskViewの事情をVCから隠蔽したいので、`maskView.changeEditMode`みたいなメソッドを用意して、そこでジェスチャーのつけ外しをしましょう

2021-03-15 02:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +    private var faces: [CGRect] = []
使ってないので消しましょう

2021-03-15 02:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        if filterImageView == nil  {
スペースが1つ多いですね

2021-03-15 02:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +    private var modeChanger: UISegmentedControl?
`makeTools`以外で使われてないので、プロパティ保持する必要はなさそう

2021-03-15 02:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +    private var toolSlider: UISlider?
こっちも`sliderAction`で`sender.value`を渡すようにするとプロパティ保持が不要になりそう

2021-03-15 02:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +            let y = (1 - sourceRect.origin.y) * imageView.bounds.height - height
一時変数を作らず、直接`CGRect`のイニシャライザに代入して良さそうです

2021-03-15 02:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        let zoom = min(xZoom, yZoom)
求めてるのは比率なので`ratio`の方が意味が分かりやすいと思います

2021-03-15 02:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +                equalTo: toolView.bottomAnchor, constant: -20).isActive = true
constantの20が同じ意味の場合は、変数として名付けをした方が理解しやすくなります

2021-03-15 02:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/Vision/FaceDetection.swift
> +extension CGImagePropertyOrientation {
このロジックが大きなハマりポイントだったので、公式リファレンスのリンクをつけておくと良いと思います

2021-03-15 02:57 UTC, TakahiroAnamizu commented on InstaExt/docs/クラス図.plantuml
> +  @IBOutlet frameの基準用ビュー: UIView
何のframeか具体的に記述して欲しいです

2021-03-15 02:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        let faceRects = convertRects(sourceRects: faces, imageView: sourceImageView)
メソッドを工夫するとコメント不要になると思います
例えば `convertRects(from normRects: [CGRect], to view: UIImageView)`など
(normは正規化のnormalizeの省略)

2021-03-15 02:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        let faceRects = convertRects(sourceRects: faces, imageView: sourceImageView)
さらに to viewをframeを引数にすると、どのView座標でも変換できる便利メソッドになったりしますね

2021-03-15 02:59 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +            maskView?.addGestureRecognizer(UIPanGestureRecognizer(target: maskView,
wantなので対応するかお任せで

2021-03-15 02:59 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +    private var toolSlider: UISlider?
wantなので対応はお任せ

2021-03-15 03:00 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        let faceRects = convertRects(sourceRects: faces, imageView: sourceImageView)
wantなのでお任せで

2021-03-15 04:55 UTC, saganoH commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +            maskView?.addGestureRecognizer(UIPanGestureRecognizer(target: maskView,
selectedSegmentIndexを渡してgestureの切り替えを行うメソッドに置き換えました。

2021-03-15 04:55 UTC, saganoH commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +    // MARK: - public
修正しました

2021-03-15 04:59 UTC, saganoH commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +    private var faces: [CGRect] = []
空の配列を削除しました

2021-03-15 04:59 UTC, saganoH commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        if filterImageView == nil  {
修正しました。

2021-03-15 05:09 UTC, saganoH commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +    private var modeChanger: UISegmentedControl?
メソッドの中に置きました

2021-03-15 05:10 UTC, saganoH commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +    private var toolSlider: UISlider?
viewDidLayoutSubviews()でもスライダの値を使っているので、こっちはそのままにしようと思います。

2021-03-15 05:18 UTC, saganoH commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +            let y = (1 - sourceRect.origin.y) * imageView.bounds.height - height
yの計算でheightを使っているので、変数を作った方がわかりやすいかなと思っていますが、どうでしょうか？

2021-03-15 05:23 UTC, saganoH commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        let zoom = min(xZoom, yZoom)
その通りですね、修正しました。

2021-03-15 05:26 UTC, saganoH commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +                equalTo: toolView.bottomAnchor, constant: -20).isActive = true
余白的な意味では同じですが、上下の余白が今の設定ではたまたま同じ、というだけなので同じ変数にしない方がいいかなと思っています。

2021-03-15 05:29 UTC, saganoH commented on InstaExt/InstaExt/Vision/FaceDetection.swift
> +extension CGImagePropertyOrientation {
コメントで追記しました。

2021-03-15 05:35 UTC, saganoH commented on InstaExt/docs/クラス図.plantuml
> +  @IBOutlet frameの基準用ビュー: UIView
修正しました。

2021-03-15 05:47 UTC, saganoH commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        let faceRects = convertRects(sourceRects: faces, imageView: sourceImageView)
修正しました。

2021-03-15 05:56 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +            let y = (1 - sourceRect.origin.y) * imageView.bounds.height - height
変数にする意味があるということで了解です

2021-03-15 05:57 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +                equalTo: toolView.bottomAnchor, constant: -20).isActive = true
目的が違うということですね、了解です

2021-03-15 07:30 UTC, TakahiroAnamizu requested changes

2021-03-15 07:30 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +    func changeEditMode(mode: Int) {
MaskViewから見ると欲しいのは`Int`ではなくモードになるので、enumを用意してあげると良いですね
もし、segmentの要素が追加された場合、今のままでは実行時エラーで落ちるまで気づかないかもしれませんが、enumの場合は、switchの分岐でビルドエラーになり事前に察知することができます(default使わず分岐する前提)

2021-03-15 07:30 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +    func changeEditMode(mode: Int) {
今後の拡張性を意識して概念を抽出し名付けをするなど考慮できるといいですね
こんなケースもあるという紹介です、修正は不要

2021-03-15 07:30 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +    func drawCycle(faceBounds: [CGRect]) {
VCなど使う側からすると`drawCircle`は誤解が生まれそうなメソッド名ですね
`mask(faces: [CGRect])`など違和感ない名前にしたいです

2021-03-15 08:02 UTC, saganoH commented
### 対面レビュー指摘
* 自分で説明する際に伝わりにくそう、と思う部分は事前に5分くらいで資料作っておくと良い
　* sourceImageに揃えなかった理由
　* 座標の変換が必要だったViewとImageの関係性など
　* 設計思想が伝わる図
* FaceDetectionクラスから受けとる[CGRect]はFaceDetectionクラスで変換したほうが良さそう？
　→sourceImageではなくsourceImageViewに合わせてスケールを戻しているため、EditorVCで変換したほうがコンパクトだった
* 顔のRectに対して、ぼかしの円を外接ではなく内接にしている理由は？
　→受け取っているRectが顔（円）の外接のようなサイズであるため、内接にすることでより顔のサイズに近い円にできて自然であるため
* convertRectsが、初見だと何をしているか不明、顔を変換していることがわかる命名の方がベター
* Extensionは別ファイルにした方がよい

2021-03-15 08:23 UTC, saganoH commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +    func drawCycle(faceBounds: [CGRect]) {
drawLineに合わせて（作る側の考えで）命名してしまってました、、、
修正しました。

2021-03-15 08:28 UTC, saganoH commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +    func changeEditMode(mode: Int) {
>MaskViewから見ると欲しいのはIntではなくモード

自分でも違和感あった部分だったので、直します

2021-03-16 00:44 UTC, saganoH commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +    func changeEditMode(mode: Int) {
Intはsegmentの変化によって受け取るものだから、どこかで吸収させる必要があることは変わらない
地味に考えることが多い＆優先順位低いためTODOに記載して保留

2021-03-16 01:08 UTC, saganoH commented
>convertRects

顔のスケールを変換していることがわかるように修正

>Extensionは別ファイルにした方がよい

一箇所のみで使っているextensionはファイル直下で良い
他で使っていないことがわかりやすいように、fileprivateへ変更

2021-03-16 01:19 UTC, TakahiroAnamizu approved these changes

2021-03-16 02:13 UTC, merged