Card 216
saganoH/InstaExt pull request #23
Opened 2021-03-17 05:02 UTC by saganoH

https://trello.com/c/OnNmuhpA/216-8-%E8%AA%8D%E8%AD%98%E3%81%97%E3%81%9F%E9%A1%94%E3%81%AE%E9%81%B8%E6%8A%9E

2021-03-17 05:49 UTC, TakahiroAnamizu requested changes
EditVCから遷移するときにdelegateの解放をしてないのでしましょう(FaceDetectionも漏れてます)
`EditVC.viewWillDisappear()`で解放するのが良いと思います

2021-03-17 05:49 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +    private var buttons: [UIButton] = []
この配列はFaceButtonの方がいいですね

また宣言はこういう書き方もできます
`private var button = [FaceButton]()`

2021-03-17 05:49 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +        buttons = []
`buttons.removeAll()`の方がわかりやすいと思います

2021-03-17 05:49 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +    private func maskFaceOn(frame: CGRect) {
On／Offでほぼ同じロジックなので、ここは共通にしておきたいですね
三項演算子を使うと綺麗にかけます
```
let color = isOn ?? UIColor.white.cgColor : UIColor.black.cgColor
context.setFillColor(color)
```

2021-03-17 05:49 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/Vision/FaceButton.swift
> +        }
単純な分岐は三項演算子を使うと綺麗に書けますので、紹介までに
```
layer.borderColor = isOn ?? UIColor.orange.cgColor : UIColor.green.cgColor
isOn.toggle()
```

2021-03-17 06:27 UTC, saganoH commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +        buttons = []
一括で消す方法があったんですね、ありがとうございます。

2021-03-17 06:28 UTC, saganoH commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +    private var buttons: [UIButton] = []
ありがとうございます、修正しました。

2021-03-17 06:53 UTC, saganoH commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +        buttons = []
removeFromSuperview()ですでにviewに載っているボタンを消し、removeAll()でボタンの存在自体を消す、と理解

2021-03-17 07:40 UTC, saganoH commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +    private func maskFaceOn(frame: CGRect) {
すごい、スマートになりました
ありがとうございます

2021-03-17 07:44 UTC, saganoH commented on InstaExt/InstaExt/Vision/FaceButton.swift
> +        }
ありがとうございます
toggleで反転できるのは初めて知りました
適用したらとてもスッキリしました

2021-03-17 08:20 UTC, TakahiroAnamizu requested changes

2021-03-17 08:20 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +            button.removeFromSuperview()
コード理解度を上げるためにここで `button.delegate = nil` を追加して解放を明示的にしておきましょう

2021-03-17 08:23 UTC, TakahiroAnamizu requested changes
すみません追加でもう1点
FaceButtonの役割を考えると、VisionではなくMaskProcessに配置する方が適切だと思います

2021-03-17 09:40 UTC, taketomato requested changes

2021-03-17 09:40 UTC, taketomato commented on InstaExt/InstaExt/Vision/FaceButton.swift
> +        isOn.toggle()
おそらく ON の場合がグリーンと思うので、`toggle` してから色更新した方が色の対応が素直になるように思いました。

2021-03-17 09:40 UTC, taketomato commented on InstaExt/InstaExt/Vision/FaceButton.swift
> +class FaceButton: UIButton {
`FaceButton`という名前が初見だと何をするクラスかわかりませんでした。

アプリを触ってコード読んで
* 領域を表す
* タップ可能
* ON/OFF の状態を持ちトグル可能

という機能であることがわかりましたが、悩んだ末 `FaceButton` よりいい名前は思い浮かびませんでした。。。

2021-03-17 09:40 UTC, taketomato commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        let modeChanger = UISegmentedControl(items: ["描画", "顔選択"])
この文字列について、初見だとどう使えばいいのか、どう動くのかがわからなかったです。

ぼかしだと `なぞってぼかす` `顔をぼかす` あたりの方がわかりやすそうです。
でも `なぞってモザイク` `顔をモザイク` は日本語としておかしいので、共通で `なぞる` `顔認識` くらいが落とし所ですかね。

`顔選択` (顔マスクの ON / OFF ができること) は別途アラートなどで説明した方がユーザ体験はよくなると思いました。

UX の一つの意見なので、修正必須ではないです。

2021-03-18 00:37 UTC, saganoH commented on InstaExt/InstaExt/Vision/FaceButton.swift
> +        isOn.toggle()
確かにそうですね、修正しました。

2021-03-18 00:38 UTC, saganoH commented on InstaExt/InstaExt/MaskProcess/MaskView.swift
> +            button.removeFromSuperview()
追記しました！

2021-03-18 00:59 UTC, saganoH commented on InstaExt/InstaExt/Vision/FaceButton.swift
> +class FaceButton: UIButton {
`FaceButton`よりは`FaceFrameButton`の方がまだわかりやすいですかね、、、

2021-03-18 01:00 UTC, saganoH commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        let modeChanger = UISegmentedControl(items: ["描画", "顔選択"])
初見でわかりづらい部分の指摘、とても助かります。
初回のみアラートを出す方向で少し調べてみます。

2021-03-18 01:03 UTC, taketomato commented on InstaExt/InstaExt/Vision/FaceButton.swift
> +class FaceButton: UIButton {
よく考えたら`Face`かどうかはこのクラスは知らないので、`TogglableFrame` でどうでしょう。

2021-03-18 01:11 UTC, saganoH commented on InstaExt/InstaExt/Vision/FaceButton.swift
> +class FaceButton: UIButton {
なるほど、今回はたまたま顔に使われている、というだけですもんね。
となると、このクラス内で`face`とか`detection`とか使わない方が良さそうですね。

2021-03-18 02:49 UTC, saganoH commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        let modeChanger = UISegmentedControl(items: ["描画", "顔選択"])
モード名は`なぞる``顔認識`にして、初回起動時のみアラートが出るようにしてみました。

2021-03-18 02:57 UTC, saganoH commented on InstaExt/InstaExt/Vision/FaceButton.swift
> +class FaceButton: UIButton {
顔を意識しないクラスとしてButtonクラスを全体的にリネームしました

2021-03-18 04:17 UTC, TakahiroAnamizu requested changes

2021-03-18 04:17 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        if UserDefaults.standard.bool(forKey: "notFirst") == false {
今後UserDefaultsを使うことになった時、Keyが何を指しているのか明確になっている方がいいです
例えば`skipEditorDescription`とかはどうでしょう？

2021-03-18 04:18 UTC, taketomato approved these changes
修正ありがとうございます！
すごくわかりやすくなりましたね♪

2021-03-18 04:20 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        if UserDefaults.standard.bool(forKey: "notFirst") == false {
あとBoolなので、この書き方の方がスマートですね
```
if !UserDefaults.standard.bool(forKey: "notFirst") 
```

2021-03-18 04:37 UTC, saganoH commented on InstaExt/InstaExt/ViewController/EditorViewController.swift
> +        if UserDefaults.standard.bool(forKey: "notFirst") == false {
・ずっとデータが残る＝初回起動に何か処理を加えるとしたら同じkeyを使うという思考だったため、処理の内容で命名してしまっていた
・他に初回起動処理を追加した場合、同じkeyにしてしまうと複数処理のうちどれか一つ通ったらフラグが変わることになってしまう、基本は個別に持つべき
・単純に、editorVCから見るとnotFirstはなんなのかわかりずらい

認識のずれを理解して、納得したので修正しました。

2021-03-18 04:53 UTC, TakahiroAnamizu approved these changes

2021-03-18 04:53 UTC, merged