Card 145
saganoH/InstaExt pull request #3
Opened 2021-01-28 06:27 UTC by saganoH

https://trello.com/c/OexLsZ6M/145-8-%E5%86%99%E7%9C%9F%E4%BF%9D%E5%AD%98%E6%A9%9F%E8%83%BD%E5%AE%9F%E8%A3%85-35

2021-01-28 06:56 UTC, TakahiroAnamizu requested changes

2021-01-28 06:56 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ImageDelivery.swift
> +            let alert = UIAlertController(
1行目はそのまま書きますね
```
UIAlertController(title: "",
                  message: "",
                  preferredStyle: .alert)
```

2021-01-28 06:56 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MainViewController.swift
> +            PHPhotoLibrary.requestAuthorization { status in
循環参照のリスクがあるので、弱参照にしましょう

2021-01-28 06:56 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MainViewController.swift
> +            imageDelivery.savePhoto(image: image, completion: { (alert) in self.showAlert(alert: alert) })
ここのcompletionも弱参照へ

2021-01-28 06:56 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MainViewController.swift
>      func showPHPicker(phPicker: PHPickerViewController)
前回の指摘で漏れてますが、DeviceDelegate > ImageDeliveryDelagateへリネームした方が良さそう
また、定義箇所をImageDeriveryファイルにした方が関連性がはっきりしていて良いです

2021-01-28 06:56 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MainViewController.swift
>      func showPHPicker(phPicker: PHPickerViewController)
そして、VC実装のメインスレッド実行も弱参照へ

2021-01-28 06:56 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MainViewController.swift
> +        if let image = mainImageView.image {
画像がない場合は、アラートなしで何も起きないのは意図通りですか？

2021-01-28 06:56 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/ImageDelivery.swift
> +            let closeAction: UIAlertAction = UIAlertAction(
権限チェックでキャンセルがあるということは、拒否しても何かしら操作ができると期待することになりますが仕様的に大丈夫ですか？

2021-01-28 07:28 UTC, saganoH commented on InstaExt/InstaExt/ImageDelivery.swift
> +            let closeAction: UIAlertAction = UIAlertAction(
（会話メモ）
拒否してもインスタのみ利用できる
→それなら保存ボタンを押してすぐ権限チェックが良さそう

2021-01-28 07:28 UTC, saganoH commented on InstaExt/InstaExt/MainViewController.swift
> +        if let image = mainImageView.image {
現状は意図通り
今後の検討事項として保留します

2021-02-01 02:37 UTC, TakahiroAnamizu approved these changes

2021-02-01 02:37 UTC, merged