Card 148
saganoH/InstaExt pull request #4
Opened 2021-02-03 02:10 UTC by saganoH

https://trello.com/c/6PF4Kmkb/148-10-%E3%81%BC%E3%81%8B%E3%81%97%E6%A9%9F%E8%83%BD%E5%AE%9F%E8%A3%85-7

2021-02-03 06:18 UTC, TakahiroAnamizu requested changes

2021-02-03 06:18 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/EditorViewController.swift
> +        processFilter()
入れ子にせず、`viewWillAppear`で呼んだ方が独立してることが分かって嬉しいです

2021-02-03 06:18 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/EditorViewController.swift
> +        guard let selectedFilter = selectedFilter else {
メソッドの先頭に持っていきましょうか

2021-02-03 06:18 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/EditorViewController.swift
> +    private let mainViewController = MainViewController()
編集完了時の戻る用？だと残念ながら別オブジェクトになるので、期待通りに動作しないと思います
一旦消して再検討してみてください

2021-02-03 06:18 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MainViewController.swift
> +        cell.backgroundColor = UIColor.systemGray
仮置きだと思いますが、ボタンにタイトルがあると嬉しいです

2021-02-03 06:18 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/Filter.swift
> +        else { return image }
`else`は改行なしでお願いします

2021-02-04 00:32 UTC, saganoH commented on InstaExt/InstaExt/EditorViewController.swift
> +    private let mainViewController = MainViewController()
途中で使わなくなって消すの忘れてました。。。

2021-02-04 00:35 UTC, saganoH commented on InstaExt/InstaExt/MainViewController.swift
> +        cell.backgroundColor = UIColor.systemGray
ボタンのデザインを、画像として設定するのかラベルとして設定するのか考え中です
（画像として設定するとダークモードで分岐しないといけなくなりますが、流石にアイコンとか設定したい、、、）

一旦ラベルを仮置きします

2021-02-04 02:16 UTC, TakahiroAnamizu approved these changes

2021-02-04 02:16 UTC, merged