[task] card_174 編集画像の合成実装
saganoH/InstaExt pull request #9
Opened 2021-02-15 06:28 UTC by saganoH

https://trello.com/c/Y0ArXMLM/174-5-%E7%B7%A8%E9%9B%86%E7%94%BB%E5%83%8F%E3%81%AE%E5%90%88%E6%88%90%E5%AE%9F%E8%A3%85-4

2021-02-15 08:01 UTC, nomadmonad reviewed
いくつかコメントしました。

わかりづらかったら口頭でも説明するので、穴水さん交えて話しましょう。

2021-02-15 08:01 UTC, nomadmonad commented on InstaExt/InstaExt/EditorViewController.swift
> +        self.navigationController?.popViewController(animated: true)
自分のプロパティを参照するときに書き方のブレがあります。
他のファイル・クラスにも同じようなブレがあるので、どちらかに統一してあると読みやすいです。

* この行のように`self`を書いてから参照する場合
* L.43の`imageComposition`のようにプロパティ名をそのまま書く場合

これは感想レベルのコメントで、変更必須じゃないです。
`self`をつける・つけないは、人やプロジェクトによって意見が変わりやすいものです。
個人的には`self`があった方がわかりやすいと思いますが、配属されたプロジェクトの書き方にあわせる、くらいの考えを持っていれば良いと思います。

2021-02-15 08:01 UTC, nomadmonad commented on InstaExt/InstaExt/ImageComposition.swift
> +    func process(sourceImageView: UIImageView, filterImageView: UIImageView) -> UIImage? {
ラベルに型の名前が入っているのは冗長に感じます。

引数の型を変えないとならない場合、ラベルも変える必要が出てきます。
なので、型名は削除して下のような形にすると簡潔に書けると思いました。
`func process(source: UIImageView, filter: UIImageView) -> UIImage?`

意見レベルのコメントなので、変更はお任せです。

2021-02-15 08:01 UTC, nomadmonad commented on InstaExt/InstaExt/ImageComposition.swift
> +            return self
機能について質問です。
リサイズに失敗したとき、失敗したことが分からなくて良いのでしょうか？

多分、ここで`resizedImage`をアンラップ失敗しても画像処理を続けられるようなコードになっていると思います。
この処理でこの後の処理が破綻しないか、何かしら失敗したことをユーザーに通知した方が良いのか、ということが判断できていません。

別途穴水さん交えて教えてもらえると助かります。

2021-02-15 08:01 UTC, nomadmonad commented on InstaExt/InstaExt/ImageComposition.swift
> +        UIGraphicsEndImageContext()
L.66の`guard`でアンラップに失敗した時、`UIGraphicsEndImageContext()`が呼ばれずに終わります。
リソースリークの可能性があるので、ここは修正しましょう。

アンラップ失敗時の`return`前に`UIGraphicsEndImageContext()`を呼び出しても良いです。

それ以外に、`defer`を使ってもまとめられます。
この行を消して、L.63とL.64の間に`defer {UIGraphicsEndImageContext()}`を追記するとメソッドの終了時に必ず呼ばれるよう変わります。

2021-02-15 08:01 UTC, nomadmonad commented on InstaExt/InstaExt/ImageComposition.swift
> +        UIGraphicsEndImageContext()
ここもL.71と同じようにリソースリークを起こしかねないので、見直しお願いします。

2021-02-15 08:01 UTC, nomadmonad commented on InstaExt/InstaExt/MainViewController.swift
> +    func setEditoredImage(image: UIImage) {
`Editor`は名詞なので、`setEditedImage`でも良さそうに思います！

感想レベルのコメントで、変更はお任せです。

2021-02-15 08:01 UTC, nomadmonad commented on InstaExt/InstaExt/ImageComposition.swift
> +        if sourceImage.size.width > sourceImage.size.height {
このままの条件でも良いですが、extensionなのでこういうメソッド書いて呼び出すのはどうでしょう？

```Swift
extension UIImage {
    // メソッド名は適当なので考えてみてください
    func is横長の画像() -> Bool { 
        return size.width > size.height
    }
}
```

感想レベルのコメントで、変更はお任せです。

2021-02-15 08:01 UTC, nomadmonad commented on InstaExt/InstaExt/MainViewController.swift
> +
余分なスペースかタブ入ってるので消しましょう。

2021-02-16 01:56 UTC, TakahiroAnamizu requested changes

2021-02-16 01:56 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/EditorViewController.swift
> +    private let imageComposition = ImageComposition()
このプロパティは`doneAction`でしか使ってないので、メソッド内定義でもいいかも
好みの問題なのでお任せです

2021-02-16 01:56 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/EditorViewController.swift
> +        let mainViewController = navi?.viewControllers[(navi?.viewControllers.count)!-2] as! MainViewController
ここの強制アンラップも安全なものにしましょう

2021-02-16 02:20 UTC, saganoH commented on InstaExt/InstaExt/EditorViewController.swift
> +        self.navigationController?.popViewController(animated: true)
selfつけないと使えない部分の参照をわかりやすくするために、必要のないselfは省略する方向で修正しました。

2021-02-16 02:20 UTC, saganoH commented on InstaExt/InstaExt/ImageComposition.swift
> +    func process(sourceImageView: UIImageView, filterImageView: UIImageView) -> UIImage? {
納得したので、そのように変更します。

2021-02-16 02:27 UTC, saganoH commented on InstaExt/InstaExt/MainViewController.swift
> +    func setEditoredImage(image: UIImage) {
その通り、修正しました。英語の弱さが露呈してしまいました。

2021-02-16 02:28 UTC, saganoH commented on InstaExt/InstaExt/MainViewController.swift
> +
削除しました。

2021-02-16 02:36 UTC, saganoH commented on InstaExt/InstaExt/ImageComposition.swift
> +        if sourceImage.size.width > sourceImage.size.height {
納得したので修正しました。

2021-02-16 02:48 UTC, saganoH commented on InstaExt/InstaExt/ImageComposition.swift
> +            return self
実際の使用でnilが入ることは起こり得ないため、nilが入ったら落ちるよう変更しました。

2021-02-16 02:49 UTC, saganoH commented on InstaExt/InstaExt/ImageComposition.swift
> +        UIGraphicsEndImageContext()
一度変数に入れて、アンラップ前に`UIGraphicsEndImageContext()`を呼ぶように修正しました

2021-02-16 03:05 UTC, saganoH commented on InstaExt/InstaExt/ImageComposition.swift
> +        UIGraphicsEndImageContext()
修正しました

2021-02-16 04:04 UTC, saganoH commented on InstaExt/InstaExt/EditorViewController.swift
> +    private let imageComposition = ImageComposition()
確かにそうですね、移動します。

2021-02-16 04:27 UTC, saganoH commented on InstaExt/InstaExt/EditorViewController.swift
> +        let mainViewController = navi?.viewControllers[(navi?.viewControllers.count)!-2] as! MainViewController
修正しました。

2021-02-16 04:45 UTC, TakahiroAnamizu requested changes

2021-02-16 04:45 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/EditorViewController.swift
> +        let mainViewController = navi.viewControllers[(navi.viewControllers.count)-2] as! MainViewController
強制キャストがあるのでこれも直しましょう

2021-02-16 04:45 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/MainViewController.swift
> +        let editorViewController = storyboard!.instantiateViewController(identifier: "editorViewController") as! EditorViewController
ここの強制キャストも直しましょう

2021-02-16 04:45 UTC, TakahiroAnamizu commented on InstaExt/InstaExt/EditorViewController.swift
> +        guard let resultImage = compositedImage else {
ここのガードは何もなしで問題ないですか？
想定してない状態だと思うので、`fatalError`で落としても良いかも

2021-02-16 05:03 UTC, saganoH commented on InstaExt/InstaExt/EditorViewController.swift
> +        let mainViewController = navi.viewControllers[(navi.viewControllers.count)-2] as! MainViewController
修正しました。

2021-02-16 05:06 UTC, saganoH commented on InstaExt/InstaExt/EditorViewController.swift
> +        guard let resultImage = compositedImage else {
まとめてガードに入れて`fatalError`になるよう修正しました。

2021-02-16 05:14 UTC, saganoH commented on InstaExt/InstaExt/MainViewController.swift
> +        let editorViewController = storyboard!.instantiateViewController(identifier: "editorViewController") as! EditorViewController
修正しました。

2021-02-16 05:24 UTC, TakahiroAnamizu approved these changes

2021-02-16 05:36 UTC, nomadmonad approved these changes

2021-02-16 05:40 UTC, merged